CREATE TABLE blocks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user INTEGER REFERENCES users(id) NOT NULL,
    category_id TEXT NOT NULL,
    block_title TEXT NOT NULL,
    block_file NOT NULL,
    block_description TEXT NOT NULL,
    optional_details TEXT,
    date_updated TIMESTAMP DEFAULT now() NOT NULL,
);