CREATE TABLE blocks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) NOT NULL,
    user_name TEXT NOT NULL,
    category_id TEXT NOT NULL,
    block_title TEXT NOT NULL,
    block_file TEXT NOT NULL,
    block_description TEXT NOT NULL,
    optional_details TEXT,
    date_updated TIMESTAMPTZ NOT NULL DEFAULT now()
);