CREATE TABLE block_feedback (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    block_id INTEGER REFERENCES blocks(id) NOT NULL,
    feedback TEXT NOT NULL,
    date_provided TIMESTAMP DEFAULT now(),
    userId INTEGER REFERENCES users(id) NOT NULL,
    flagged BOOLEAN
);