const cloudinary = require('cloudinary').v2;
const multer = require('multer')
const { CLOUD_NAME, CLOUD_API_KEY, CLOUD_API_SECRET } = require('../../config')
const { CloudinaryStorage } = require('multer-storage-cloudinary')


cloudinary.config({
    cloud_name: CLOUD_NAME,
    api_key: CLOUD_API_KEY,
    api_secret: CLOUD_API_SECRET,
});

const storage = new CloudinaryStorage({
    cloudinary: cloudinary,
    folder: 'app',
    resource_type: 'auto'
})

const upload = multer({ storage: storage })
//problem - cloudinary is currently looking for a locally stored asset - but server is not correct path
// need to figure out how to temp store the file? then pass it to cloudinary
//figure out how to use multer to temp store file data to pass to cloudinary

const AssetService = {
 
    uploadAsset(block_file, category_id) {
        cloudinary.uploader.upload(block_file, 
         {  folder: category_id,
            resource_type: 'auto' },
          function(err, image) { console.log();
            console.log("** File Upload");
            if (err) { console.warn(err); }
            console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
            });
    },

}

module.exports =  AssetService